# This is a basic workflow to help you get started with Actions

name: sudipta

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
Business/Project Name: SUDIPTA MONDAL
Business/Project Name: SUDIPTA MONDAL

Description: একটি পার্সোনাল ওয়েবসাইট যা কলিং সুবিধা সহ ব্যবহারের জন্য তৈরি করা হয়েছে।

Style: নীল রঙের আধুনিক ডিজাইন

Content to include on website:
  - About: আমার সম্পর্কে সংক্ষিপ্ত বিবরণ।
  - Contact: আমার সাথে যোগাযোগের জন্য তথ্য এবং কলিং অপশন।
Description: একটি পার্সোনাল ওয়েবসাইট যা কলিং সুবিধা সহ ব্যবহারের জন্য তৈরি করা হয়েছে।

Style: নীল রঙের আধুনিক ডিজাইন

Content to include on website:
  - About: আমার সম্পর্কে সংক্ষিপ্ত বিবরণ।
  
  - Contact: আমার সাথে যোগাযোগের জন্য তথ্য এবং কলিং অপশন।


  
